version: '3.3'


networks:
  frontend:
    external:
      name: imixs-proxy-net 
  backend: 
  

services:


  ################################################################
  # elasticsearch
  #  - runs on manager node
  ################################################################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      
    volumes:
      - elk-data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == manager-001
    networks:
      - backend




        
  ################################################################
  # filebeat
  #  - runs on manager node
  ################################################################      
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.6.1
    command: setup -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"] 
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker          
    networks:
      - backend


  ################################################################
  # Kibana
  #  - runs on manager node
  ################################################################      
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    depends_on:
      - elasticsearch

    deploy:
      labels:
        #traefik.port: "5601"
        #traefik.frontend.rule: "Host:logging.mycloud.com"
        #traefik.docker.network: "imixs-proxy-net" 
      replicas: 1
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == manager-001

    networks:
      - frontend
      - backend


volumes:
  elk-data:
