# Ingress Route HTTP
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{YOUR-WORKER-HOST-NAME}`)
    services:
    - name: whoami-service
      port: 80
    # uncomment to redirect http -> https
    #middlewares: 
    #- name: redirect

# Ingress Route HTTPS
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{YOUR-WORKER-HOST-NAME}`)
    kind: Rule
    services:
    - name: whoami-service
      port: 80
  tls:
    certResolver: default

    

    
    