version: '3.2'

services:
  app:
     image: prom/prometheus
     volumes:
       - $PWD/management/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     ports:
       - 9090:9090
     deploy:
       labels:
         #traefik.port: "9090"
         #traefik.frontend.rule: "Host:myhost.com"
         # traefik.frontend.auth.basic.users: "admin:xxxxxxxxxxxxxxxxxxxx"
         #traefik.docker.network: "imixs-proxy-net" 
       placement:
         constraints:
           - node.role == manager
     
networks:
   default:
    external:
      name:  imixs-proxy-net
