version: '3.2'

services:


  ################################################################
  # Prometheus 
  #  - runs on manager node
  ################################################################
  prometheus:
    image: prom/prometheus
    volumes:
      - $PWD/management/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      labels:
        #traefik.port: "9090"
        #traefik.frontend.rule: "Host:prometheus.myhost.com"
        # traefik.frontend.auth.basic.usersFile: /path/.htpasswd   
        #traefik.frontend.auth.basic.users: "admin:$$axxxxxxxxxxxxxxxxxxxxxxxxx"
        #traefik.docker.network: "imixs-proxy-net" 
      placement:
        constraints:
          - node.role == manager
    networks:
      - frontend
      - backend     


  ################################################################
  # The promethes node exporter 
  #   - runs on every node
  ################################################################
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    volumes:
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc:/host/proc:ro
    deploy:
      mode: global


     
  ################################################################
  # Grafana
  #  - runs on manager node
  ################################################################
  grafana:
    image: grafana/grafana
    volumes: 
      - grafana-data:/var/lib/grafana
    deploy:
      labels:
        traefik.port: "3000"
        traefik.frontend.rule: "Host:grafana.myhost.com"
        traefik.docker.network: "imixs-proxy-net" 
      placement:
        constraints:
          - node.role == manager
    networks:
      - frontend
      - backend



volumes:
  grafana-data:



networks:
  frontend:
    external:
      name: imixs-proxy-net 
  backend: 
  

