# Traefik Dashboard
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: traefik-dashboard
spec:
  routes:
  - match: Host(`{YOUR-WORKER-HOST-NAME}`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
